server.port=${PORT:8080}

app.jwt.secret=${APP_JWT_SECRET:Y2hvb29zZS1hLXNlY3VyZS1hbmQtc3Ryb25nLWtleS1mb3Itand0LXNpZ25pbmctMjU2LWJpdHM=}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

# PostgreSQL Database Configuration (Render)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-dafq1j740ujc73ce0cag-a:5432/expansedb}
spring.datasource.username=${DB_USERNAME:expansedb_user}
spring.datasource.password=${DB_PASSWORD:aSAuJoyaAxArDtmzfM23vFSWQZaU9SJF}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false